<a href="https://colab.research.google.com/github/SDS-AAU/SDS-master/blob/master/00_notebooks/AM2021_pg1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Peergrade Øvelse

![](https://source.unsplash.com/Imwgit84NGo)

Ideen med denne øvelse er at give dig en mulighed bruge (næsten) alt vi har lært indtil videre med et nyt eksempel og uden tidspres. Du må rigtig gerne arbejde sammen med din gruppe dog er det vigtigt, at du har styr på alt selv. Brug også gerne Teams til at diskuttere problemer med andre. 
Alt som skal bruges af kode findes i de notebooks, som der blev brugt til undervisning.

I denne øvelse kommer I til at arbejde med lineær algebra på en lidt anden måde end tidligere, selvom tilgangen vil være den samme. I stedet for at arbejde x og y i traditionel forstand med, for eksempel, tid og pris på akserne, vil I blive introduceret til produktionsoptimering med to forskellige produkter på hver akse. Det kan være, at I har set lignende opgaver som del af mikroøkonomi.
  
Forestil jer, at I skriver et projekt i samarbejde med det lokale industri-bageri. I skal hjælpe butikken med at optimere produktion af cookies of muffins, for at få det maksimale udbytte. I har fået en oversigt over deres produktionsomkostninger, og skal nu forsøge at give butikken indblik i produktionsforholdet mellem muffins og cookies, ud fra forskellige parametre. 


**Pris** 
* Cookies bliver solgt til 32 kroner pr. kilo
* Muffins bliver solgt til 27 kroner pr. kilo

**Produktionsomkostninger**
* Cookies koster 21.72 kroner pr. kilo at producere
* Muffins koster 17.28 kroner pr. kilo at produere

**Arbejdstimer**
* Cookies koster 0.7 arbejdstimer at producere pr. kilo
* Muffins koster 0.9 arbejdstimer at producere pr. kilo


#### Opgave 1.1:
Bageriet har indkøbt ingredienser til muffins og cookies for 50.000kr i forbindelse med denne produktionscyklus.

Start med at visualisere produktionsforholdet mellem cookies og muffins, altså, hvor mange i kan producere af henholdsvis muffins og cookies, med de 50.000, i har til rådighed. Til dette skal i bruge produktionsprisen på cookies (y) og produktionsprisen på muffins (x).

Dette kan skrives i **generel form** som: $21.72*y + 17.28*x = 50000$

Omskriv dette til **hældningsafskæringsform** (slope-intercept form), så y står alene, og plot linjen visuelt. 


In [ ]:
# pakke-import

import numpy as np
np.set_printoptions(suppress=True)

import matplotlib.pyplot as plt

In [ ]:
# Start med at definere x - brug numpy's linspace funktion til generere 1000 observationer mellem 0 og 3000

# definer jeres y ud fra ovenstående algebraiske udtryk


# Navngiv jeres x- og y-akse.
plt.xlabel('Muffins')
plt.ylabel('Cookies')

#plot linjen 


Det første plot giver dog kun et overblik, i hvordan produktionen af muffins og cookies kan fordeles, med udgangspunkt i de tilgængelige resurser. I målet om at finde den optimale fordeling, for at få maksimalt udbytte, er der også andre ting der skal overvejes.

#### Opgave 1.2:
Produktion af kager har flere omkostninger tilknyttet end blot ingredienser, herunder, arbejdstimer. Bageriet har tilknyttet **200** arbejdstimer til produktionen af muffins og cookies. 1 kilo cookies tager 0.7 arbejdstime at producere, hvor muffins tager 0.9 arbejdstime.

Omskriv dette til den **generelle form**, og herefter til **hældningsafskæringsform**.

Gentag herefter plottet fra opgave 1.1, og tilføj linjen for arbejdsomkostninger for muffins og cookies.



In [ ]:
# Start med at definere x - brug numpy's linspace funktion til generere 1000 observationer mellem 0 og 3000

# inddrag y fra opgave 1 (y1)

# tilføj jeres algebraiske udtryk for arbejdsomkostninger (y2)


# Navngiv jeres x- og y-akse.
plt.xlabel('Muffins')
plt.ylabel('Cookies')

#plot linje y1 - giv den farven rød ("red")

#plot linje y2 - giv den farven blå ("blue")


Ud fra ovenstående plot, kan vi nu få et indblik i mængden af henholdsvis muffins og cookies bageriet skal producere for at optimere udbyttet, med udgangspunkt i de 2 variable i har adgang til.

### Opgave 1.3
Selvom den grafiske fremstilling giver et visuelt overblik, har i brug for at finde den præcise kilomængde af muffins og cookies vi skal producere ud fra denne opstilling. Vores to lingninger kan skrives som denne augmented matrix:

$$
\left[
  \begin{matrix}
    21.72 & 17.28 \\
    0.07 & 0.09 \\
  \end{matrix}
  \left|
    \,
    \begin{matrix}
      50000  \\
      200  \\
    \end{matrix}
  \right.
\right]
$$

- Prøv at finde løsningen 'i hånden' først ved hjælp af **eliminationsmetoden** (i numpy), i kan muligvis huske tilgangen fra første [undervisningsgang](https://colab.research.google.com/github/RJuro/am-21/blob/main/HA_Math_1_1_Linear_Systems_edited.ipynb#scrollTo=DqGpjUg71znB). Skriv gerne kommentar i koden hvilke rækkeoperationer du bruger.


- Herefter kan i anvende sympy til at foretage udregningen direkte symbolisk.

- Du kan se en ny måde at løse opgaven med scipy nederst - det er også der, hvor du kan tjekke, om din løsning passer.


In [ ]:
# definer matrix først
matrix = np.array([[21.72,17.28,50000],
[0.07,0.09,200]])

In [ ]:
#importer sympy pakker
from sympy import * #importer alt fra Sympy
from sympy.solvers.solveset import linsolve #importer linalg solver

#definer vores symboler (c for cookies, m for muffins)
c, m = symbols('c, m') 

# Brug linsolve til at finde den præcise skæring mellem produktionsomkostninger (y1) og arbejdsomkostninger (y2), og gem resultatet i xy_graphical

# Print resultatet: xy_graphical


FiniteSet((1400.96618357488, 1132.58185721954))


In [ ]:
# en 3. løsning som kan bruges (ny mulighed - bare for at se, den findes)
# vi kommer dog til at bruge sympy 👆 en del ifm calculus...og derfor er det fint lige at se på det allerede nu

from scipy import linalg

A = np.array([[21.72, 17.28],
       [ 0.07,  0.09]])

b = np.array([50000, 200])

x = linalg.solve(A,b)

In [ ]:
print(x)

[1400.96618357 1132.58185722]


### Opgave 1.4 
Nu hvor vi har fundet den "optimale" mængde af muffins og cookies i kg (vi runder til hele kg og husk du kan ikke rigtigt runde op fordi du ikke har ingredienser til det), kan vi udregne hvor meget bageriet kommer til at tjene, baseret på vores begrænsede informationer. 

In [ ]:
# Gem mængden af cookies i variablen qcookies - husk at runde ned til hele tal. 
qcookies=
# Gem mængden af muffins i variablen qmuffins - husk at runde ned til hele tal.
qmuffins=

#udregn den samlede omsætning for muffins (27*qmuffins) og cookies(32*qcookies)  
result=

#print resultatet, med teksten "dkk er vores omsætning for denne produktionsrunde"
print(result, "dkk er vores omsætning for denne produktionsrunde")

### Opgave 2

I opgave 1 tilgik vi problemet ved hjælp af grafisk visualisering, og løsning fra hældningsafskæringsform samt Gauss elimination  (+ automatisk løsning til tjek). I opgave 2 skal I løse samme problemstilling ved hjælp af multiplikativ invers. 

#### Opgave 2.1

Definer numpy arrays med $A$ som matrix_a og $\vec{b}$ som vector_b. Du må gerne copy-paste fra 1.3 (scipy demo)

In [ ]:
# generér matrix_a
matrix_a = 

print(matrix_a)

# generér vector_b
vector_b = 
print(vector_b)

[[21.72 17.28]
 [ 0.07  0.09]]
[[50000.]
 [  200.]]


#### Opgave 2.2
Beregn $A^{-1}$ ved at bruge numpy funktion til dette.

In [ ]:
#opgave 2.2.1
matrix_a_inverse = 

print(matrix_a_inverse)

Vis, at $A^{-1}A = I$

In [ ]:
# opgave 2.2.2

identity_matrix=

print(identity_matrix)

Vi ved, at $I\vec{x}=\vec{x}$ og derfor bliver $A^{-1}A\vec{x}=A^{-1}\vec{b}$ til $\vec{x} = A^{-1}\vec{b}$

Beregn $\vec{b}$ 

In [ ]:
# opgave 2.2.3

vector_x=

print(vector_x) 

[[1400.9663]
 [1132.5815]]
